=== gematik/api-ePA/src/implementation_guides/ig-schema-definition.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$ref": "#/definitions/StructureDefinition",
	"$version": "1.2.1",
	"definitions": {
		"CardinalityDefinition": {
			"description": "Constraints on the amount of the XDS folder or document in order to support that structured document in the electronic health record system.",
			"type": "object",
			"properties": {
				"min": {
					"type": "string"
				},
				"max": {
					"type": "string"
				},
				"unique": {
					"description": "The value 'true' means that solely one document/folder with the availablility status 'approved' is allowed to be registered with the given metadata combination. False means that multiple instances may be submitted.",
					"type": "boolean"
				}
			},
			"required": [
				"min",
				"max"
			],
			"additionalProperties": false
		},
		"FolderDefinition": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"value": {
					"anyOf": [
						{
							"title": "value",
							"type": "object",
							"properties": {
								"code": {
									"type": "string"
								},
								"codeSystem": {
									"type": "string"
								},
								"displayName": {
									"type": "string"
								},
								"deprecatedFrom": {
									"description": "The following value is deprecated and should not be used from this date on. Useage of alternative value with same name instead is recommended",
									"type": "string",
									"format": "date"
								},
								"desc": {
									"$ref": "#/definitions/DescriptionDefinition"
								}
							},
							"required": [
								"code",
								"codeSystem",
								"displayName"
							],
							"additionalProperties": false
						},
						{
							"title": "value",
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"code": {
										"type": "string"
									},
									"codeSystem": {
										"type": "string"
									},
									"displayName": {
										"type": "string"
									},
									"deprecatedFrom": {
										"description": "The following value is deprecated and should not be used from this date on. Usage of alternative value with same name instead is recommended.",
										"type": "string",
										"format": "date"
									},
									"desc": {
										"$ref": "#/definitions/DescriptionDefinition"
									}
								},
								"required": [
									"code",
									"codeSystem",
									"displayName"
								],
								"additionalProperties": false
							}
						},
						{
							"title": "value",
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					]
				}
			},
			"required": [
				"name",
				"value"
			],
			"additionalProperties": false
		},
		"DescriptionDefinition": {
			"title": "desc",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"language": {
						"type": "string"
					},
					"#text": {
						"type": "string"
					}
				},
				"required": [
					"language",
					"#text"
				],
				"additionalProperties": false
			}
		},
		"DocumentDefinition": {
			"type": "object",
			"properties": {
				"version": {
					"description": "The version of the document format.",
					"type": "string"
				},
				"name": {
					"description": "The name of the specific document.",
					"type": "string"
				},
				"description": {
					"description": "The description of the specific document.",
					"type": "string"
				},
				"canonicalUrl": {
					"description": "A canonical URL of the structure definiton of the specific document.",
					"type": "string"
				},
				"metadata": {
					"title": "metadata",
					"type": "array",
					"items": {
						"$ref": "#/definitions/FolderDefinition"
					}
				},
				"documentCardinality": {
					"$ref": "#/definitions/CardinalityDefinition"
				},
				"implementationArtifact": {
					"description": "This usage specification is not intended for verifying structured documents.",
					"type": "boolean"
				},
				"maxDocumentHistory": {
					"description": "Defines the maximum amount of deprecated elements to be kept in a XDS RPLC chain (approved document does not count). Oldest entries may be deleted when this limit gets exeeded",
					"type": "integer"
				},
				"deidentification": {
					"description": "Provides all information to de-identify (anonymize) a FHIR document of the associated FHIR profile. All FHIR elements addressed by a FHIRPath in the list 'allowList' shall be applied in order to de-identify the document without changing its content.",
					"type": "object",
					"properties": {
						"allowList": {
							"$ref": "#/definitions/DeidentificationDefinition"
						}
					}
				}
			},
			"required": [
				"name",
				"description",
				"metadata",
				"documentCardinality"
			],
			"additionalProperties": false
		},
		"StructureDefinition": {
			"type": "object",
			"properties": {
				"name": {
					"description": "The technical name of the structured document.",
					"type": "string"
				},
				"description": {
					"description": "The overall description of the structured document.",
					"type": "string"
				},
				"igVersion": {
					"description": "Version information of the Implementation Guideline file",
					"type": "string"
				},
				"guidelineDefinition": {
					"description": "A link to the (FHIR) implementation guideline including its version.",
					"type": "object",
					"properties": {
						"url": {
							"type": "string",
							"format": "uri"
						},
						"version": {
							"type": "string"
						}
					},
					"required": [
						"url"
					],
					"additionalProperties": false
				},
				"folderCardinality": {
					"$ref": "#/definitions/CardinalityDefinition"
				},
				"validFromDate": {
					"description": "Date from which the structured document is accepted (upload/download) by ePA-server.",
					"type": "string",
					"format": "date"
				},
				"clientReadOnlyFromDate": {
					"description": "Date from which the structured document is accepted (only download) by ePA-server. The upload is rejected by ePA-server",
					"type": "string",
					"format": "date"
				},
				"type": {
					"description": "The collection type of the structured document - either 'mixed', 'uniform' or 'atomic'.",
					"type": "string"
				},
				"metadata": {
					"$ref": "#/definitions/FolderDefinition"
				},
				"elements": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/DocumentDefinition"
					}
				}
			},
			"required": [
				"name",
				"description",
				"guidelineDefinition",
				"validFromDate",
				"type",
				"elements"
			]
		},
		"DeidentificationDefinition": {
			"description": "a list of fhir path elements arranged as list of paths for each possible profile",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"profile": {
						"description": "Profile canocial-url",
						"type": "string"
					},
					"fhir": {
						"description": "Resource profile specific list of fhir path entries defining allowed elements for research data submission. An addressed element shall appear in a pseudonymized document with the same path and including all child elements.",
						"type": "array",
						"items": {
							"type": "string"
						}
					}
				},
				"required": [
					"profile",
					"fhir"
				]
			}
		}
	}
}

=== gematik/api-ePA/src/implementation_guides/ig-researchDataSubmissionTracking.json
{
	"name": "Research Data Submission Tracking",
	"description": "Detailled record of submitted and withdrawn (if applicable) pseudonymous documents for research purposes.",
	"igVersion": "1.0.1",
	"guidelineDefinition": {
		"url": "https://github.com/gematik/api-ePA/blob/2.5.1/src/implementation_guides/researchDataSubmissionTrackingList.json",
		"version": "1.0.2"
	},
	"folderCardinality": {
		"min": "1",
		"max": "1",
		"unique": false
	},
	"validFromDate": "2023-01-01",
	"type": "atomic",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "technical",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "Technische Dokumente",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Technische Dokumente, die nicht für Leistungserbringer berechtigt und einem Versicherten oder Vertreter nicht direkt im ePA-FdV zur Anzeige gebracht werden"
				}
			]
		}
	},
	"elements": [
		{
			"version": "1.0.0",
			"name": "Aufzeichnungsliste Datenfreigabe Forschung",
			"description": "This document is a detailed record of all pseudonymous documents submiited to a research data center for medical research data analysis",
			"canonicalUrl": "https://github.com/gematik/api-epa/src/sharedResearchData/researchDataSubmissionTrackingList.json",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "ADM",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Administratives Dokument",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Anträge, Aufklärung, Bescheinigungen; auch juristische Dokumente, Vereinbarungen und Verträge; Anmeldungen, Regelungen, Einwilligungen, Bestellungen, Rechnungen, Bescheide, Anordnungen (im juristischen Sinne), Aufträge, Ausweise (außer medizinische Ausweise wie Impfpässe, siehe Konzept AUS ('Medizinischer Ausweis')), Meldungen, Qualitätssicherungsdokumente"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:researchDataSubmissionTracking:v1.0",
						"codeSystem": "2.25.154081344090540725127779452347992051720",
						"displayName": "Aufzeichnungsliste Forschungsdatenfreigabe"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/json"
					]
				}		
			],
			"documentCardinality": {
				"min": "0",
				"max": "1"
			},
			"maxDocumentHistory" : 10
			
		}
	]
}
